### ISSUE TITLE
Support alternative file structure

### ISSUE THREAD

**Issue by dustinspecker** [dustinspecker/generator-ng-poly#100]
Currently, ng-poly only supports a structure such as:

```
app/
├── home/
│   ├── door/
│   ├── home.js
│   ├── home.css
│   ├── home.tpl.html
│   ├── home-controller.js
│   └── home-controller_test.js
├── app.js
└── index.html
```

but should be able to *also* support one such as:

```
app/
├── home/
│   ├── controllers/
│   │   ├── home-controller.js
│   │   └── home-controller_test.js
│   ├── door/
│   ├── views/
│   │   ├── home.css
│   │   └── home.tpl.html
│   └── home.js
├── app.js
└── index.html
```

This would potentially, inherently, add support (by adding to the app.js module) for a structure such as: 

```
app/
├── controllers/
│   ├── home-controller.js
│   └── home-controller_test.js
├── views/
│   ├── home.css
│   └── home.tpl.html
├── app.js
└── index.html
```

**Comment by jack10** [comment]
+1, would love that scructure. I already seperated them manually like this. But with many Modules/Submodules its a lot of a work.

**Comment by drejohnson** [comment]
Would be nice to just have a prompt that lets you specify the directory structure you want.

**Comment by dancancro** [comment]
I don't like the last part where files from all different functional units seem to be dumped into the same place.  Can you make that impossible?

I'm curious why you don't want to just take a stand here.  Can you explain why it is good for people to do the same thing (organize their files) in multiple ways?

For reference, [here](https://docs.google.com/spreadsheets/d/1r8rJy2Q5p5QORYKcye93UECwOlSgFL24c5fyF7dqhaM/edit#gid=1607194899) are all my arguments against unnecessary variety.  If I had to rank things that should be done the same way by everyone, uniformity of file organization would be the thing I support most.

**Comment by dustinspecker** [comment]
Hey, Dan. The third structure isn't really a feature of this, but more of a side effect of enabling the second structure. I'm not going to make it impossible to do the third one, but if we notice people are gravitating towards that then we should discuss this again. (We definitely don't want to encourage a structure like that.)

I see where you're coming from with keeping to one structure. At the moment, I don't personally lean towards the first or second over the other. The goal of this generator is to encourage a modular/feature structure. Both of these achieve that goal, in my opinion. For now, I think it makes sense to support this second structure as it is becoming more popular. I don't see a lot of value in disabling the second structure and "forcing" everyone to migrate to the second. In the future, I believe it would be beneficial to revisit this and see if one is way more popular to justify dropping support for the other - hopefully with a simple upgrade process for existing projects.

**Comment by DefunctExodus** [comment]
:+1: 

Right now this is the only thing that is preventing me from using this builder in my production environment.

Personally (which is what it comes down to) I am a fan of [this](https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub) structure.

**Comment by OSOM-DEV** [comment]
+1

**Comment by alexhawkins** [comment]
This is fantastic work Dustin. It's the best Angular generator I've come across. And Polymer + Angular Material + ES6 support?? Are you kidding me! It's right in line with John Papa and Tod Mottos's style guide in terms of keeping everything modular based on features. I think this is important, especially when your app starts to grow in size. However, I would like to have the option to use the  second architectural pattern above. It's just a little more clear to me. I also like  John Papa's naming conventions. Instead of naming our modules app and home, better would be app.module and home.module/ home.controller  etc...It's just a littler more clear. Also to have a core module so we don't have to keep adding ui-router to every controller.  Unless that's how you think it should be? It's also definitely possible to manually change the names but then all the units tests get screwed up and well...it's just a pain. But man, the ES6 support is great. Great work. Keep it coming.

**Comment by dustinspecker** [comment]
Thanks, Alex! I agree that naming the module files to app-module.js would be better. This would also be a good time to create app-route.js files and move the route definitions from the module definition file. The core module is another great idea. I'll throw up some issues later to track these. Thank you for the suggestions.

**Comment by dustinspecker** [comment]
83129b96bf0e6d6bf859233645dcf54a30b802f9 Add support for separating components by types within each module.
