### ISSUE TITLE
Dropping ng-poly options dicussion

### ISSUE THREAD

**Issue by dustinspecker** [dustinspecker/generator-ng-poly#119]
ng-poly asks too many questions and I'd like to fix that.

The options I want to drop first are:
1. Using $scope instead of ControllerAs - We should encourage ControllerAs
2. ~~Defining functions inline instead of passing~~
```javascript
// quit offering this
angular
  .module('module')
  .controller('HomeCtrl', function () {...});

// only offer this
angular
  .module('module')
  .controller('HomeCtrl', HomeCtrl);

function HomeCtrl() {...}
```
3. ~~Using anonymous functions instead of named functions - I believe this will become completely useless if we drop defining functions inline like above.~~
4. Drop Angular 1.2 support - If you're creating a new project, it should use 1.3. I don't think any of the templates are specific to 1.3 (yet).

I'd also like to make assumptions with support for command line options to override (--port=8000, etc)
1. Assume localhost for host and port 3000
2. Assume app will be created in app folder
3. Assume unit tests will be created in app folder
4. Assume UI Router will be used instead of ngRoute

I'm open to more suggestions and reasons to not drop these.

**Comment by xak2000** [comment]
I like the ideas except controllerAs.
I using angular not too long but still can't understand the real advantage of using controllerAs instead of scope. Even if using controllerAs in many cases I still need scope api so I must inject `$scope` anyway for watches etc.

And if I using controllerAs then i need do something like `$scope.$watch('nameOfControllerInControllerAsInRoute.myVar', function () {})`
So I couple my controller code to my route definitions in module (because `controllerAs` defined in route) or to template code (`ng-controller='HomeCtrl as homeCtrl'`).

With $scope I just do `$scope.$watch('myVar', function () {})`

Maybe i'm doing something wrong. But for now I more like classic scope syntax then controllerAs.

**Comment by wilsonwc** [comment]
I would totally agree with all of your assumptions above except the port, that should probably still be a configurable value by the generator.  When Angular 1.4 drops the option for the new router should be the default.  The assumptions above fall inline with the generally accepted angular styleguide recommendations. https://github.com/johnpapa/angular-styleguide

**Comment by dustinspecker** [comment]
ControllerAs removes uncertainties when having nested controllers (difficult to know which scope the object is coming from and the object may become "duplicated" and won't sync properly). It also helps to treat controllers as classes. In regards to $scope.$watch, the first parameter can be a function, which I believe most of us do. Todd Motto has a great [post](http://toddmotto.com/digging-into-angulars-controller-as-syntax/) showing this off.


The port would still be configurable if the user runs `yo ng-poly --port=9000`. That's a good call about the new router coming out. That one should still be a prompt.

**Comment by xak2000** [comment]
I read many articles about `controllerAs` but no one of them convince me.
The only advantage is not messing up scope's variables in nested controllers. But nested controllers is already a bad thing. I think we never should use variables from parent controller in nested controller. If we need them we must pass them.

But all other things is disadvantages for me.

We must use `myVerySpecialVm.title` instead of `title` in templates. This template already binded to one controller. By router or by attribute. And I already know which `title` it is. Placing `myVerySpecialVm.` every time is just a garbage.

We must use function to watch variables. I think is is slower then just using var name. But not sure about this. In every case we loss brevity of code.

We must keep controller's names uniqueness. We can't just name all our controllers `as vm` as in many examples in articles that glorify controllerAs techniques. If we do this then we lose the first "advantage" of using nested controllers without names collisions.

So I think using `conrollerAs` is more taste of preference then killer feature that all must use.
But for about making only this options available when generating new project I think is not very big problem. For example now I working on porject with this option enabled and remove `controllerAs` boilerplate after generating each directive. I already don't remember why. :)

**Comment by dustinspecker** [comment]
8d28a6a691692ad993d31b9f4f1bee3b8de9729c remove pass function option
9f1f00cc8b28a368f66b290b63fcd17a98564995 remove named function option

**Comment by dustinspecker** [comment]
28ea4c23aee6b75ac44e6307c6b619bd2da7d538 Assume host, port, appDir, and unitTestDir and offer ability to override.

Leaving the controllerAs option for now. Leaving the router choice as not sure if people will choose UI Router or New Angular Router (future).
