### ISSUE TITLE
Don't install unnecessary modules

### ISSUE THREAD

**Issue by busches** [dustinspecker/generator-ng-poly#133]
A lot of modules are installed that aren't used, for instance even if you select to use ES6, `gulp-coffee` and `gulp-coffeelint` are still installed. What are you thoughts about wrapping them in the package.json with conditionals? Or is the goal to allow the user to swap between multiple flavors at once? If so, you should be able to remove the following questions, since all the packages are installed either way:
`[?] Which is the preferred markup language?`
`[?] Which is the preferred application scripting language?`
`[?] Which is the preferred style language?`

**Comment by dustinspecker** [comment]
Hi. Originally, the idea was that teams could create files with different languages. These questions are in place to set the default language to use for generating files instead of always having to pass a language option with each generator command.

In practice, I wouldn't really encourage mixing languages. Maybe we should remove this and then conditionally include modules and modify the Gulp files. Would definitely be less bloat for new projects.

Are there folks mixing languages?

**Comment by busches** [comment]
I'm a fan of keeping the questions and then adding conditionals in the files to reduce bloat. 

No one in my organization is mixing languages to my knowledge.  As you said, I'm not sure anyone would recommend it.

**Comment by wilsonwc** [comment]
I like this thought, and actually went through my generated gulp files and simplified a lot because I wasn't using coffee, es6 or typescript.  Then I could actually remove the use of $.filter in some cases once I simplified the file regexes in the gulpfile.js.

**Comment by dustinspecker** [comment]
1e9641641a1a1b77dfa1e5da6e0f1e7293db6358 Think this ought to do it. Hopefully I didn't miss anything.
