### ISSUE TITLE
Way to add existing web components

### ISSUE THREAD

**Issue by welldonesir** [dustinspecker/generator-ng-poly#138]
The elements like core-* & paper-* are in the bower folder but i they are not accessible by /components.
How is one supposed to "enable" them if they are already in bower.
I would assume there is a way to tell bower to include them in the project inside the automatic bower inclusion section but i can't find anything.

Regards

**Comment by dustinspecker** [comment]
Hi. I think this thread still works: https://github.com/dustinspecker/generator-ng-poly/issues/72. I can verify this tonight and provide a better response (and add a section to the README).

**Comment by welldonesir** [comment]
So if i understand this correctly, the way to go is to add the appropriate polymer element in the gulpfile.
If this is the case, i would like to propose a different approach.
The project even has POLY in its name so why not include all the webcomponents in the bowercomponents folder per default and add/remove them via bower itself.
Personally i don't want to write grunt/gulp files, this is the main reason i use boilerplates.

**Comment by dustinspecker** [comment]
I *think* we can also add main overrides to the Bower.json instead of having to touch Gulp. That's better in my opinion.

I agree that it could be easier/improved. I'm hesitant to include all core and Paper elements because that's a lot of dependencies. I think people should be aware of just how many would be pulled in. Definitely open to suggestions.

**Comment by dustinspecker** [comment]
112cf46a3b59ddaf4ef13e317c62b2c3d29ef673 Closing this as a how to was added to the README.
