### ISSUE TITLE
ng-poly generates empty module_name-routes.js file when --empty is present

### ISSUE THREAD

**Issue by xak2000** [dustinspecker/generator-ng-poly#152]
I think when we generate an empty module then we doesn't want to generate any routes for it. We can add them later if we want.

My use case for example is generating new module for new directive. It is good practice to place directives in their own modules I think. So I don't need any files except simple module definition. And of course this module never will contain any routes.

------------
Also this is offtopic but I want to ask why you decided to separate module and route definitions and add suffix `-module` to module file? I explored [Angular New Router](http://angular.github.io/router/getting-started) a bit and it's default structure is opposite. Module names is just module names and hasn't any suffixes. All routes defined in main `app` module. Also modules is actually **components** with their own folders each contains template and optionally module definition file. Controller defined in this file too. Each module (component) can have only one main controller if I understand correctly. Also controller can have methods for router (`canActivate` for examle). So it's name must be ModuleName + suffix `Controller`.

So this is completely different structure then we have now. And after add `-module` suffix to module file this is even more different then now. :)

**Edit**
I thought about this question again and maybe it has more sense when **all** structure will be new. With new structure we will have only 1-2 files in each component. Template and *optionally* module definition which will also have controller of this module, it's config etc. With this structure we always know which file is what. It is only TWO files.. So maybe it has sense. But with current structure we have many files in each folder so maybe `-module` suffix is really useful.

**Comment by dustinspecker** [comment]
Good catch! An empty module should not have a -route.js. You can definitely safely delete that for now.

I made this change to better align with John Papa's guide lines. We recommends splitting the routes config from the module.

Yeah, Angular New Router is going to bring some interesting challenges. I'm probably going to make an update to use the 'Controller' suffix instead of 'Ctrl' (also better aligns with John Papa's guide lines). I'm curious if the community is going to shift towards that component structure or stick with the modular structure.

In regards to the modular structure, there is a $componentLoaderProvider we can use to modify the template loading functionality. We can have a map and return the correct template path there. The problem is here to automatically create this map, but I think a Gulp plugin could solve it pretty easily. We could also use the $componentLoaderProvider to change the controller suffix.

**Comment by dustinspecker** [comment]
d88378fadf902ec79ebf8ce8708c527c07c7f684 Fixed.
