### ISSUE TITLE
Angular appears before jQuery on minification

### ISSUE THREAD

**Issue by jboothe** [dustinspecker/generator-ng-poly#179]
When creating a "prod" build, Angular code is placed in the minified file before jQuery code causing Angular to use jqLite instead of full version of jQuery. Alternatively, when creating a "dev" build, jQuery is inject properly in before Angular in the ```<!-- bower:js -->``` tags of the index page. 

Upon inspection of the gulp/build.js file, it appears that angularFileSort (v1.1.1), is used just prior to concat. 
```
...
.pipe($.if(isProd, $.angularFilesort()))
.pipe($.if(isProd, $.concat('app.js')))
...
```
Are there any work-arounds or alternative libs to solve this? Thanks in advance.

**Comment by dustinspecker** [comment]
Angular Filesort is only used for the Angular app's source code, none of the Bower deps, so that shouldn't be an issue.

We use Wiredep which looks at Bower dependencies and verifies correct loading order. Since, Angular doesn't specify a dependency on jQuery, we'll need to override that. [Wiredep has an example of overriding.](https://github.com/taptapship/wiredep#bower-overrides) Try adding jQuery as a dependency for Angular. This should force jQuery to be loaded before Angular.

If that doesn't work let me know.

**Comment by jboothe** [comment]
Dustin, I'm always impressed with your timely responses. Thank you. 

It took a few tries to determine that path was relative to the angular/bower.json file. For others that may have the same issue, I added this line to bower.json file and we're good!

```
"overrides": {
    "angular": {
      "main": [ "../jquery/dist/jquery.js", "./angular.js" ]
    }
  }
```

Also, in the event that others search on the original error I received due to the incorrect dependency order, I'll include it here:
```
jqLite#on() does not support the `selector` or `eventData` parameters
```

**Comment by xak2000** [comment]
Maybe it will be better to do someting like:

"overrides": {
    "angular": {
      "dependencies": {
        "jquery": "1.x"
      }
    }
  }

I don't know if it will work.

**Comment by jboothe** [comment]
@xak2000 - your suggestion does place jquery before angular but angular-translate ends up before angular.

**Comment by xak2000** [comment]
Ok got it.
Then we need place ALL dependencies from original angular's bower.js.
I thought that `overrides` section adds dependencies to the list. But it replaces them.

**Comment by xak2000** [comment]
It's strange because angular-translate depends on angular. And we didn't change anything about it..

**Comment by dustinspecker** [comment]
Hmmm. [angular-translate's bower.json](https://github.com/angular-translate/angular-translate/blob/master/bower.json) doesn't list Angular as a dependency.

@jboothe If you add an override for angular-translate as well, that should fix it. Might want to also throw up an issue asking them to add the dep or see if they have a reason for not adding it. It's also usually better to override dependencies instead of adding to main (in case a future version changes the main file), but if main works better for you, then not a big deal.

**Comment by dustinspecker** [comment]
I'm going to close this for now, but if any more related issues arise please feel free to reopen this.
